name: Jack Nash
favicon: null
layout_spectrum: 0.864983837120235
typography_spectrum: 0.8288262644782662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030405'
    - '#07b8ea'
    - '#00ffff'
    - '#0000ff'
    - '#074e63'
  brandStrength: 0.11636619293130934
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
